name: aegis3_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.0
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.0
  cached_network_image: ^3.3.0

  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.9
  image_picker: ^1.2.1
  crypto: ^3.0.3

  socket_io_client: ^2.0.3+1
  
  #Time formatting for messages
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
